spring:
  sql.init.mode: always
  application:
    name: review
  datasource:
    url: jdbc:mysql://localhost:3306/microservices-db
    username: user
    password: pwd
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

server.port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring.config.activate.on-profile: docker
spring.datasource.url: jdbc:mysql://mysql:3306/microservices-db

server.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
