services:
  product-service:
    build: product
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

  review-service:
    build: review
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      replicas: 2

  front-product-service:
    build: frontProductComposite
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway-service:
    build: gateway
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  mysql:
    image: mysql:8.0.32
    mem_limit: 512m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=microservices-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  eureka:
    build: discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    mem_limit: 512m
    ports:
      - "8761:8761"

  config-server:
    build: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native  # native profile is mandatory otherwise it tries default git
    mem_limit: 512m
    volumes:
      - /home/jroure/config-repo:/config-repo