
spring:
  application:
    name: frontProductComposite
server.port: 8000

app:
  product-service:
    host: localhost
    port: 8001
  review-service:
    host: localhost
    port: 8002

resilience4j.timelimiter:
  instances:
    review:
      timeoutDuration: 2s
management.health.circuitbreakers.enabled: true
resilience4j.circuitbreaker:
  instances:
    review:
      allowHealthIndicatorToFail: false
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      ignoreExceptions:
        - cat.tecnocampus.frontproductcomposite.application.services.ProductDoesNotExistException

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true

---
spring.config.activate.on-profile: docker

app:
  product-service:
    host: product-service
    port: 8080
  review-service:
    host: review-service
    port: 8080


server.port: 8080

