spring.config.import: "configserver:"

config:
  server:
    usr: "dev-usr"
    pwd: "dev-pwd"

spring:
  application.name: gateway
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://config-server:8888 #http://localhost:8888
    username: ${config.server.usr}
    password: ${config.server.pwd}

---
spring.config.activate.on-profile: docker

spring.cloud.config.uri: http://config-server:8888