spring:
  application:
    name: frontProductComposite

server.port: 8000

app:
  product-service:
    host: localhost
    port: 8001
  review-service:
    host: localhost
    port: 8002

---
spring.config.activate.on-profile: docker

app:
  product-service:
    host: product-service
    port: 8080
  review-service:
    host: review-service
    port: 8080

server.port: 8080

