spring:
  sql.init.mode: always
  application:
    name: review
  datasource:
    url: jdbc:mysql://localhost:3306/microservices-db
    username: user
    password: pwd
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

server.port: 8002

---
spring.config.activate.on-profile: docker
spring.datasource.url: jdbc:mysql://mysql:3306/microservices-db


server.port: 8080
